server {
    listen       ${PORT} default_server;
    listen  [::]:${PORT} default_server;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(js|css|jpg|jpeg|png|gif|ico|svg|mp3|webp|woff2)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location = /health {
        access_log off;
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
